### ISSUE TITLE
[ERROR] [1680062006.304793]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7effcd05c5f8>>

### ISSUE THREAD

**Issue by xmkkkkkk** [avasalya/Yolo6D_ROS#8]
Sorry to bother you, I followed your steps and got the following error, which troubled me for many days, how can I solve it? thank you very much for your help.

[ERROR] [1680062006.304793]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7effcd05c5f8>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 225, in add
    self.signalMessage(*msgs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/home/xmk/shares/share-ubuntu/6d_ws/src/yolo6d_ros/scripts/yolo6d_ros.py", line 103, in callback
    self.pose_estimator()
  File "/home/xmk/shares/share-ubuntu/6d_ws/src/yolo6d_ros/scripts/yolo6d_ros.py", line 115, in pose_estimator
    output = self.model(data).data
  File "/home/xmk/.conda/envs/yolo6d1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xmk/shares/share-ubuntu/6d_ws/src/yolo6d_ros/scripts/darknet.py", line 96, in forward
    x = self.models[ind](x)
  File "/home/xmk/.conda/envs/yolo6d1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xmk/shares/share-ubuntu/6d_ws/src/yolo6d_ros/scripts/darknet.py", line 27, in forward
    assert(H % stride == 0)
AssertionError

**Comment by avasalya** [comment]
Are you sure you are using the right version of darknet?

**Comment by xmkkkkkk** [comment]
> Are you sure you are using the right version of darknet?
Yes,Thanks for your answer！ I used another command to turn on realsense 'roslaunch realsense2_camera rs_aligned_depth.launch'   it works! Thanks again.
